run_name: test_data_mifish_noman_2024
output_dir: "../v2-results"
# marker_info:  marker_info.yaml
# Demultiplexing by amplicon or sample
raw_fastq_path: /Users/katherine.silliman/Projects/NOAA/tourmaline-dev/v2-tourmaline/test-fastqs #absolute path to raw fastq files 
trimmed_fastq_path: #trimmed files must have suffix _R[1,2].fastq.gz
sample_manifest_file: # test_mifish_pe_manifest_provided.manifest # if provided and trimming, then import to raw_fastq.qza, then trim into a new trimmed_fastq.qza. 
#if provided and not trimming, just import to fastq.qza
sample_metadata_file: # optional if no summary plotting, is this needed at all for sample step?

to_trim: True #Boolean
paired_end: True

amplicon_name: 12S-MiFish
#trimming parameters
fwd_primer: GCCGGTAAAACTCGTGCCAGC
rev_primer: CATAGTGGGGTATCTAATCCCAGTTTG
discard_untrimmed: False
minimum_length: 50
trimming_threads: 2
#quality parameters
seq_quality_cutoff: 0.85 # not used  yet
#command: snakemake --use-conda -s sample_test.Snakefile --configfile samp_config_test.yaml --cores 4
